/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function MobileModelMic(props) {
  const { nodes, materials } = useGLTF("/mobilemic.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere.geometry}
        material={materials["Material.002"]}
        position={[0.062, 3.61, 0.54]}
        rotation={[0, -0.186, 0]}
        scale={[0.195, 0.213, 0.195]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane.geometry}
        material={materials["Material.003"]}
        position={[-0.037, 3.135, 0.924]}
        rotation={[Math.PI / 2, 0, -1.385]}
        scale={[-0.053, -0.053, -0.058]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder001.geometry}
        material={nodes.Cylinder001.material}
        position={[-0.013, 2.955, 0.939]}
        rotation={[0, -0.186, 0]}
        scale={[-0.069, -0.124, -0.069]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder002.geometry}
        material={nodes.Cylinder002.material}
        position={[-0.007, 2.773, 0.934]}
        rotation={[0, -0.186, 0]}
        scale={[-0.046, -0.05, -0.046]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder003.geometry}
        material={nodes.Cylinder003.material}
        position={[-0.011, -0.789, 0.925]}
        rotation={[0, -0.186, 0]}
        scale={[0.087, 0.095, 0.134]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder004.geometry}
        material={nodes.Cylinder004.material}
        position={[-0.01, -0.934, 0.92]}
        rotation={[0, -0.186, 0]}
        scale={[0.486, 0.054, 0.508]}
      />
    </group>
  );
}

useGLTF.preload("/mobilemic.glb");

